# Generated by Django 5.1.1 on 2024-09-09 03:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=1)),
                ('body', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Excellent'), (6, 'Exceptional')], default=4)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
